version: '2'
services:
  authentication:
    build:
      context: ./authentication-api/
      dockerfile: Dockerfile
    container_name: authentication
    ports:
      - "8887:8081"
    networks:
      - app-network

  service2:
    build:
      context: ./service-order-api/
      dockerfile: Dockerfile
    container_name: service-order
    ports:
      - "8886:8082"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

