server:
  port: 8082

spring:
  security:
    jwt-secret: 9D0EB6B1C2E1FAD0F53A248F6C3B5E4E2F6D8G3H1I0J7K4L1M9N2O3P5Q0R7S9T1U4V2W6X0Y3Z
  datasource:
    url: jdbc:h2:mem:serviceorderdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  config:
    local-url: http://localhost
    services:
      user-api: ${app.config.local-url}:8081/api/users/exists