server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:serviceorderdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  config:
    local-url: http://localhost
    services:
      user-api: ${app.config.local-url}:8081/api/users


logging:
  level:
      org.springframework.web: DEBUG